
CREATE TABLE IF NOT EXISTS `reprise`
(
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `token` varchar(250) DEFAULT NULL COMMENT 'md5 de la première ligne des données du fichier des marchés',
  `nom` varchar(50) DEFAULT NULL,
  `date_debut` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_fin` timestamp NULL DEFAULT NULL,
  `etat` int(2) NOT NULL COMMENT '0 = Initialisation en cours, 1 = Analyse en cours, 2 = Terminée, 3 = Interrompue',
  `instructions_src` int(11) NOT NULL DEFAULT '0',
  `instructions_dest` int(11) NOT NULL DEFAULT '0',
  `conflits` int(11) NOT NULL DEFAULT '0',
  `erreurs` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `dest_exploitant`
(
    EXP_REF                   INT,
    UTI_REF                   INT,
    GRA_REF                   INT,
    CAT_REF                   INT,
    NAT_REF                   INT,
    CIV_REF                   INT,
    LAN_REF                   INT,
    ETP_REF                   INT,
    ACO_REF                   INT,
    ACOO_REF                  INT,
    EXP_NOM_PERS_PHYSIQUE     VARCHAR(250),
    EXP_PRENOM_PERS_PHYSIQUE  VARCHAR(250),
    EXP_RAISON_SOCIALE        VARCHAR(250),
    EXP_NOM                   VARCHAR(250),
    EXP_ENSEIGNE              VARCHAR(250),
    EXP_SIRET                 VARCHAR(250),
    EXP_CODE                  VARCHAR(250),
    EXP_CODE_COMPTABLE        VARCHAR(250),
    EXP_APE                   VARCHAR(250),
    EXP_TVAINTRACOMMUNAUTAIRE VARCHAR(250),
    EXP_VISIBLE               INT,
    EXP_VALIDE                INT,
    EXP_DATE_CESSATION DATE,
    EXP_NRUE              INT,
    EXP_NRUE_ALPHA        VARCHAR(250),
    EXP_ADRESSE           VARCHAR(250),
    EXP_CP                VARCHAR(250),
    EXP_VILLE             VARCHAR(250),
    PA_REF                INT,
    RUE_REF               INT,
    EXP_COMPLEMENTADRESSE VARCHAR(250),
    EXP_TELEPHONE         VARCHAR(250),
    EXP_PORTABLE          VARCHAR(250),
    EXP_FAX               VARCHAR(250),
    EXP_COMMENTAIRE       VARCHAR(250),
    EXP_EMAIL             VARCHAR(250),
    EXP_TITULAIRECOMPTE   VARCHAR(250),
    EXP_IBAN              VARCHAR(250),
    EXP_BIC               VARCHAR(250),
    EXP_SEPA_NUMERO_RUM   VARCHAR(250),
    EXP_SEPA_SIGNATURE_MANDAT DATE,
    EXP_PRODUCTEUR INT,
    EXP_DATE_NAISSANCE DATE,
    EXP_PHOTO_IDENTITE VARCHAR(250),
    EXP_CODERUEGDA     VARCHAR(250),
    EXP_CREATION DATE,
    EXP_MODIFICATION DATE,
    DCREAT DATE,
    UCREAT                    VARCHAR(250),
    ANC_EXP_REF               INT,
    EXP_LIEU_NAISSANCE        VARCHAR(250),
    EXP_DEPARTEMENT_NAISSANCE VARCHAR(250),
    PAN_REF                   INT,
    EXP_NUM_AGREMENT          VARCHAR(250),
    EXP_REFERENCE_RCS         VARCHAR(250),
    EXP_PERMIS_DATE DATE,
    EXP_PERMIS_LIEU           VARCHAR(250),
    EXP_PERMIS_AUT_DELIVRANCE VARCHAR(250),
    EXP_PERMIS_DATE_FIN DATE,
    EXP_CARTE_PRO_NUMERO VARCHAR(250),
    EXP_CARTE_PRO_DATE DATE,
    EXP_CARTE_PRO_DATE_FIN DATE,
    EXP_FORMATION_CONT_DATE_FIN DATE,
    EXP_TYPE_TAXIS      INT,
    EXP_COMPLEMENT_NOM  VARCHAR(250),
    EXP_TIERS_A_VALIDER INT,
    EXP_TIERS_VALIDE    INT
);

CREATE TABLE IF NOT EXISTS `dest_domaine_langue`
(
    DOM_REF     INT,
    LAN_REF     INT,
    DOM_FAMILLE VARCHAR(250),
    DOM_NOM     VARCHAR(250),
    DOM_FAC_NOM VARCHAR(250),
    DOM_MULTIPLICATEUR_NOM VARCHAR(250),
    DOM_QUANTITE_LIBELLE VARCHAR(250),
    DOM_DELIBERATION VARCHAR(250),
    DOM_DLC1_NOM    VARCHAR(250),
    DOM_DLC2_NOM    VARCHAR(250),
    DCREAT      DATE,
    UCREAT      VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS `dest_evenement`
(
    EVE_REF     INT,
    DET_REF     INT,
    EVE_DELAI_EXPIRATION VARCHAR(250),
    EVE_ACTION   VARCHAR(250),
    EVE_ORDRE   INT,
    EVE_VISIBLE INT,
    DCREAT      DATE,
    UCREAT      VARCHAR(250),
    EVE_BALISE_DATE_CREATION    VARCHAR(250),
    EVE_BALISE_DATE_RELANCE     VARCHAR(250),
    EVE_BALISE_COMMENTAIRE      VARCHAR(250),
    EVE_BALISE_EVENEMENT_NOM    VARCHAR(250),
    EVE_BALISE_SPECIFIQUE       VARCHAR(250),
    EVE_BALISE_LISTE_INFRACTION VARCHAR(250),
    EVE_BALISE_AFFICHAGE_PREPA_TOURNEE  VARCHAR(250),
    EVE_BALISE_TABLETTE         VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS `dest_evenement_langue`
(
    EVE_REF     INT,
    LAN_REF     INT,
    EVE_DESIGNATION VARCHAR(250),
    EVE_COMMENTAIRE_TYPE VARCHAR(250),
    DCREAT      DATE,
    UCREAT      VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS `dest_dossier`
(
    DOS_REF INT,
    DOM_REF INT,
    EXP_REF INT,
    DOS_NOM VARCHAR(250),
    RUE_REF INT,
    DOS_NRUE INT,
    DOS_NUM VARCHAR(250),
    DOS_DATE DATE,
    DOS_EXERCICECOMPTABLE VARCHAR(250),
    DOS_VISIBLE INT,
    DOS_COMMENTAIRE VARCHAR(250),
    DOS_MODIFICATION DATE,
    DOS_COMPLEMENTADRESSE VARCHAR(250),
    ACT_REF INT,
    DOS_EXONERATION VARCHAR(250),
    DOS_EXONERATION_DCM DATE,
    DOS_CTL_DATEDERNIER DATE,
    DOS_CTL_EMPREFDERNIER INT,
    DOS_CONTROLE INT,
    DOS_CTL_DATEACTUEL DATE,
    DOS_CTL_EMPREFACTUEL INT,
    DET_REF INT,
    DOS_NRUE_ALPHA VARCHAR(250),
    DOS_DATE_CESSATION DATE,
    DCREAT DATE,
    UCREAT VARCHAR(250),
    EMP_REF INT,
    ZV_REF INT,
    DOS_VALIDE INT,
    DOS_NUM_BON_COMMANDE VARCHAR(250),
    DLC1_REF INT,
    DLC2_REF INT,
    DOS_NRUE_2 INT,
    DOS_NRUE_ALPHA_2 VARCHAR(250),
    DOS_COMPLEMENTADRESSE_2 VARCHAR(250),
    RUE_REF_2 INT,
    DOS_TYPE_LICENCE VARCHAR(250),
    DOS_QUARTIER_ELU VARCHAR(250),
    DOS_CAPACITE_ACCUEIL VARCHAR(250),
    DOS_HEURE_OUVERTURE VARCHAR(250),
    DOS_HEURE_FERMETURE VARCHAR(250),
    ECO_REF INT,
    ECO_FAC_REF INT,
    DOS_DATE_MOD_TABLETTE DATE,
    DOS_EMP_MOD_TABLETTE INT,
    DOS_GEO_LONGITUDE VARCHAR(250),
    DOS_GEO_LATITUDE VARCHAR(250),
    DOS_PHOTO_PRINCIPALE VARCHAR(250),
    DOS_NB_FACTURE INT,
    SAC_REF INT,
    DOS_DATE_DEB_ARRETE DATE,
    DOS_DATE_FIN_ARRETE DATE,
    ED_REF INT,
    NUM_ETAB VARCHAR(250),
    DQ_REF INT,
    DOS_ADRESSE VARCHAR(250),
    DOS_VILLE VARCHAR(250),
    DOS_CP VARCHAR(250),
    DOS_NAFFAIRE_DECLARANT VARCHAR(250),
    DOS_OBJ_RESTREINT VARCHAR(250),
    DOS_DATE_AUTORISATION DATE,
    DOS_SUIVI_PART VARCHAR(250),
    DOS_NUM_MARCHE_CPP VARCHAR(250),
    DOS_NUM_ENGAGEMENT_CPP VARCHAR(250),
    DOS_CODE_SERVICE_CPP VARCHAR(250),
    DOS_NOM_SERVICE_CPP VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS `dest_dossier_etat`
(
    DET_REF     INT,
    DOM_REF     INT,
    DET_VISIBLE INT,
    DET_ORDRE   INT,
    DCREAT      DATE,
    UCREAT      VARCHAR(250),
    DET_AFFICHECODE INT
);

CREATE TABLE IF NOT EXISTS `dest_dossier_etat_langue`
(
    DET_REF     INT,
    LAN_REF     INT,
    DET_DESIGNATION VARCHAR(250),
    DCREAT      DATE,
    UCREAT      VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS `dest_dossier_instruction`
(
    DI_REF      INT,
    DOS_REF     INT,
    DET_REF     INT,
    EXP_REF     INT,
    DI_NUMERO   VARCHAR(250),
    DI_DATE_DEPOT   DATE,
    DI_MOYEN_DEPOT  VARCHAR(250),
    DI_NRUE     INT,
    DI_NRUE_ALPHA VARCHAR(250),
    RUE_REF     INT,
    DI_ADRESSE  VARCHAR(250),
    DI_CP       VARCHAR(250),
    DI_VILLE    VARCHAR(250),
    DI_COMPLEMENTADRESSE    VARCHAR(250),
    DCREAT      DATE,
    UCREAT      VARCHAR(250),
    DI_CONTACT  INT,
    DI_ARCHIVE  INT,
    DI_ARCHIVE_DATE DATE,
    ITP_REF     INT,
    DI_CODE     VARCHAR(250),
    DI_DATE_MOD_TABLETTE    DATE,
    DI_EMP_MOD_TABLETTE INT
);

CREATE TABLE IF NOT EXISTS `dest_dossier_instruction_evenement`
(
    DIE_REF     INT,
    DI_REF      INT,
    EVE_REF     INT,
    DIE_DATE_CREATION   DATE,
    DIE_DATE_EXPIRATION DATE,
    DCREAT      DATE,
    UCREAT      VARCHAR(250),
    DIE_COMMENTAIRE VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS `dest_dossier_commentaire_type_langue`
(
    DCT_REF     INT,
    LAN_REF     INT,
    DCT_NOM     VARCHAR(250),
    DCREAT      DATE,
    UCREAT      VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS `dest_dossier_document`
(
    DD_REF      INT,
    DOS_REF     INT,
    DEV_REF     INT,
    DCT_REF     INT,
    DD_AUTEUR   VARCHAR(250),
    DD_NOM      VARCHAR(250),
    DD_DATE     DATE,
    DD_COMMENTAIRE  VARCHAR(250),
    DCREAT      DATE,
    UCREAT      VARCHAR(250),
    DIE_REF     INT,
    FAO_REF     INT,
    DD_DATE_MOD_TABLETTE    DATE,
    DD_EMP_MOD_TABLETTE INT,
    DD_ANCIEN_EXP   VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS `dest_compteur`
(
    CPT_REF           INT,
    CPT_TABLE         VARCHAR(250),
    CPT_VAL           INT,
    DCREAT            DATE,
    UCREAT            VARCHAR(250)
);

-- DELETE FROM dest_exploitant;
-- DELETE FROM dest_domaine_langue;
-- DELETE FROM dest_dossier;
-- DELETE FROM dest_dossier_etat;
-- DELETE FROM dest_dossier_etat_langue;
-- DELETE FROM dest_dossier_instruction;
-- DELETE FROM dest_evenement;
-- DELETE FROM dest_evenement_langue;
-- DELETE FROM dest_dossier_document;
-- DELETE FROM dest_compteur;
