CREATE TABLE IF NOT EXISTS `dest_activite_langue`
(
    ACT_REF           INT,
    LAN_REF           INT,
    ACT_NOM           VARCHAR(250),
    DCREAT            DATE,
    UCREAT            VARCHAR(250)
);
INSERT INTO dest_activite_langue (ACT_REF,LAN_REF,ACT_NOM,DCREAT,UCREAT) values ('1','1','Marchés Municipaux',CURDATE(),'iltr');

CREATE TABLE IF NOT EXISTS `dest_groupe_activite_langue`
(
    GRA_REF           INT,
    LAN_REF           INT,
    GRA_NOM           VARCHAR(250),
    DCREAT            DATE,
    UCREAT            VARCHAR(250)
);
INSERT INTO dest_groupe_activite_langue (GRA_REF,LAN_REF,GRA_NOM,DCREAT,UCREAT) values ('1','1','Marchés municipaux',CURDATE(),'iltr');

CREATE TABLE IF NOT EXISTS `dest_compteur`
(
    CPT_REF           INT,
    CPT_TABLE         VARCHAR(250),
    CPT_VAL           INT,
    DCREAT            DATE,
    UCREAT            VARCHAR(250)
);
INSERT INTO dest_compteur (CPT_REF,CPT_TABLE,CPT_VAL,DCREAT,UCREAT) values ('33','marche','19',CURDATE(),'ILTR');
INSERT INTO dest_compteur (CPT_REF,CPT_TABLE,CPT_VAL,DCREAT,UCREAT) values ('1','compteur','32',CURDATE(),'ILTR');
INSERT INTO dest_compteur (CPT_REF,CPT_TABLE,CPT_VAL,DCREAT,UCREAT) values ('2','utilisateur','1',CURDATE(),'ILTR');
INSERT INTO dest_compteur (CPT_REF,CPT_TABLE,CPT_VAL,DCREAT,UCREAT) values ('0','activite','0',CURDATE(),'ILTR');
INSERT INTO dest_compteur (CPT_REF,CPT_TABLE,CPT_VAL,DCREAT,UCREAT) values ('3','actreffacture','21',CURDATE(),'ILTR');
INSERT INTO dest_compteur (CPT_REF,CPT_TABLE,CPT_VAL,DCREAT,UCREAT) values ('4','mode_reglement','2',CURDATE(),'ILTR');
INSERT INTO dest_compteur (CPT_REF,CPT_TABLE,CPT_VAL,DCREAT,UCREAT) values ('5','materiel','1',CURDATE(),'ILTR');
INSERT INTO dest_compteur (CPT_REF,CPT_TABLE,CPT_VAL,DCREAT,UCREAT) values ('6','employe','2',CURDATE(),'ILTR');
INSERT INTO dest_compteur (CPT_REF,CPT_TABLE,CPT_VAL,DCREAT,UCREAT) values ('8','balise_placier','91',CURDATE(),'ILTR');
INSERT INTO dest_compteur (CPT_REF,CPT_TABLE,CPT_VAL,DCREAT,UCREAT) values ('9','courrier_placier','0',CURDATE(),'ILTR');
INSERT INTO dest_compteur (CPT_REF,CPT_TABLE,CPT_VAL,DCREAT,UCREAT) values ('10','societe_document','0',CURDATE(),'ILTR');
INSERT INTO dest_compteur (CPT_REF,CPT_TABLE,CPT_VAL,DCREAT,UCREAT) values ('11','societe_document_document','0',CURDATE(),'ILTR');
INSERT INTO dest_compteur (CPT_REF,CPT_TABLE,CPT_VAL,DCREAT,UCREAT) values ('12','infraction','0',CURDATE(),'ILTR');
INSERT INTO dest_compteur (CPT_REF,CPT_TABLE,CPT_VAL,DCREAT,UCREAT) values ('13','constat','0',CURDATE(),'ILTR');
INSERT INTO dest_compteur (CPT_REF,CPT_TABLE,CPT_VAL,DCREAT,UCREAT) values ('14','balise','73',CURDATE(),'ILTR');
INSERT INTO dest_compteur (CPT_REF,CPT_TABLE,CPT_VAL,DCREAT,UCREAT) values ('15','saga','0',CURDATE(),'ILTR');
INSERT INTO dest_compteur (CPT_REF,CPT_TABLE,CPT_VAL,DCREAT,UCREAT) values ('16','saga_transaction','0',CURDATE(),'ILTR');
INSERT INTO dest_compteur (CPT_REF,CPT_TABLE,CPT_VAL,DCREAT,UCREAT) values ('17','mise_a_leau','0',CURDATE(),'ILTR');
INSERT INTO dest_compteur (CPT_REF,CPT_TABLE,CPT_VAL,DCREAT,UCREAT) values ('18','CodeInstruction','0',CURDATE(),'ILTR');
INSERT INTO dest_compteur (CPT_REF,CPT_TABLE,CPT_VAL,DCREAT,UCREAT) values ('19','marche_place','1',CURDATE(),'ILTR');
INSERT INTO dest_compteur (CPT_REF,CPT_TABLE,CPT_VAL,DCREAT,UCREAT) values ('20','marche_plan','1',CURDATE(),'ILTR');
INSERT INTO dest_compteur (CPT_REF,CPT_TABLE,CPT_VAL,DCREAT,UCREAT) values ('21','marche_point','1',CURDATE(),'ILTR');
INSERT INTO dest_compteur (CPT_REF,CPT_TABLE,CPT_VAL,DCREAT,UCREAT) values ('22','brocante_point','1',CURDATE(),'ILTR');
INSERT INTO dest_compteur (CPT_REF,CPT_TABLE,CPT_VAL,DCREAT,UCREAT) values ('23','brocante_place','1',CURDATE(),'ILTR');
INSERT INTO dest_compteur (CPT_REF,CPT_TABLE,CPT_VAL,DCREAT,UCREAT) values ('24','brocante_plan','1',CURDATE(),'ILTR');
INSERT INTO dest_compteur (CPT_REF,CPT_TABLE,CPT_VAL,DCREAT,UCREAT) values ('25','brocante_place_article','1',CURDATE(),'ILTR');
INSERT INTO dest_compteur (CPT_REF,CPT_TABLE,CPT_VAL,DCREAT,UCREAT) values ('26','brocante_affectation_place','1',CURDATE(),'ILTR');
INSERT INTO dest_compteur (CPT_REF,CPT_TABLE,CPT_VAL,DCREAT,UCREAT) values ('27','brocante_affectation_article','1',CURDATE(),'ILTR');
INSERT INTO dest_compteur (CPT_REF,CPT_TABLE,CPT_VAL,DCREAT,UCREAT) values ('28','numero_rum_sepa','0',CURDATE(),'ILTR');
INSERT INTO dest_compteur (CPT_REF,CPT_TABLE,CPT_VAL,DCREAT,UCREAT) values ('29','numero_export_sepa','0',CURDATE(),'ILTR');
INSERT INTO dest_compteur (CPT_REF,CPT_TABLE,CPT_VAL,DCREAT,UCREAT) values ('30','numero_export_pes','0',CURDATE(),'ILTR');
INSERT INTO dest_compteur (CPT_REF,CPT_TABLE,CPT_VAL,DCREAT,UCREAT) values ('31','societe_marche_numero_contrat','0',CURDATE(),'ILTR');
INSERT INTO dest_compteur (CPT_REF,CPT_TABLE,CPT_VAL,DCREAT,UCREAT) values ('32','societe_marche_mutation','0',CURDATE(),'iltr');

CREATE TABLE IF NOT EXISTS `dest_utilisateur`
(
    UTI_REF INT,
    UTI_NOM VARCHAR(250),
    UTI_ADRESSE VARCHAR(250),
    UTI_CODEPOSTAL VARCHAR(250),
    UTI_VILLE VARCHAR(250),
    UTI_PAYS VARCHAR(250),
    UTI_TELEPHONE VARCHAR(250),
    UTI_FAX VARCHAR(250),
    UTI_EMAIL VARCHAR(250),
    UTI_NUMAGREMENT VARCHAR(250),
    UTI_IDENTIFIANT VARCHAR(250),
    UTI_MDP_PLATEFORME VARCHAR(250),
    UTI_LOGO VARCHAR(250),
    UTI_ALERTE INT,
    UTI_ALERTE_TIME INT,
    UTI_MULTIMARCHE INT,
    UTI_GESTION_ELEC INT,
    UTI_ABOTITULAIRE_AUTO INT,
    UTI_TICKETSTYPES INT,
    UTI_CHEMINSITE VARCHAR(250),
    UTI_SOCIETECARTE INT,
    UTI_ADRESSECARTE VARCHAR(250),
    UTI_FACTUREMENSUELLE INT,
    UTI_MODEAFFICHAGECLIENTSPDA VARCHAR(250),
    UTI_RELANCEFACTURE INT,
    UTI_VERSRASFAC INT,
    UTI_PDA_RETOURDIRECTSOC INT,
    UTI_PDA_TICKETPERIODE INT,
    UTI_EXPORT_COMPTABLE VARCHAR(250),
    UTI_IMP_TIKET_PRESENCE INT,
    UTI_LOGOPDA INT,
    UTI_LOGOPDACHEMIN VARCHAR(250),
    UTI_GESTION_PLAN INT,
    UTI_GESTIONODP INT,
    UTI_GESTIONPLACIER INT,
    UTI_CHEMREPDONNEES VARCHAR(250),
    UTI_GOOGLE_API_KEY VARCHAR(250),
    UTI_LDAP INT,
    UTI_VERSIONLOGICIEL VARCHAR(250),
    UTI_MODELE_FACTURE VARCHAR(250),
    UTI_MODELE_TICKET VARCHAR(250),
    UTI_GESTIONROLMRE INT,
    UTI_TYPEVERSEMENT INT,
    UTI_LDAP_DOMAINE VARCHAR(250),
    UTI_CODE_GUICHET VARCHAR(250),
    UTI_NUMERO_COMPTE VARCHAR(250),
    UTI_GESTION_IMPORT INT,
    UTI_GESTION_TAS INT,
    UTI_GESTION_AUTORISATIONTICKET INT,
    UTI_NOM_COLLECTIVITE VARCHAR(250),
    UTI_GESTIONSAUVEGARDE INT,
    UTI_GESTION_INFRACTION INT,
    UTI_AFFBLOC_ENCAISSEMENT INT,
    UTI_AFFBLOC_RASSEMBLEMENT INT,
    UTI_AFFBLOC_INFRACTION INT,
    UTI_GESTIONGENERATION INT,
    UTI_IDENTIFIANTCLIENTCOMPTABLE VARCHAR(250),
    UTI_LETTREAPPLICATIVE VARCHAR(250),
    UTI_MONNAIESUPPORT VARCHAR(250),
    UTI_NUMERONATIONALEMETTEUR VARCHAR(250),
    UTI_CODEOPERATION VARCHAR(250),
    UTI_GESTION_CONSTAT INT,
    UTI_MODIF_FACTURE INT,
    UTI_GROUPE_TARIF INT,
    UTI_IMPRIMANTE_CODEBARRE VARCHAR(250),
    UTI_GESTION_SUIVI_DOSSIER INT,
    UTI_GESTION_COURRIER INT,
    UTI_GESTION_ABONNEMENT INT,
    UTI_GESTION_AUTORISATION INT,
    DCREAT DATE,
    UCREAT VARCHAR(250),
    UTI_SITE_AIDE_IDENTIFIANT VARCHAR(250),
    UTI_SITE_AIDE_MDP VARCHAR(250),
     UTI_GESTION_RECU INT,
     UTI_EXPORT_BDF INT,
     UTI_GESTION_ZONE INT,
     UTI_EXTERNALISATION_RUE INT,
     UTI_EXPORTSAGA INT,
     UTI_GESTION_TARIFPERIODE INT,
     UTI_GESTION_NUMTITRE INT,
     UTI_GESTION_RECU_AUTOMATIQUE INT,
     UTI_GESTION_CANDIDATURE INT,
     UTI_GESTION_INSTRUCTION INT,
     UTI_GESTION_TAS_PDA INT,
     UTI_GESTION_VERSEMENT_RECU INT,
     UTI_GESTION_COMMISSION INT,
     UTI_GESTION_ARRETE_ELEMENT INT,
     UTI_GESTION_PHOTO_ID INT,
     UTI_EXPORT_INDIGO_TITRE INT,
     UTI_CODE_COLLECTIVITE VARCHAR(250),
     UTI_CODE_BUDGET VARCHAR(250),
     UTI_GESTION_TVA_BELGE INT,
     UTI_GESTION_EXP_NUM_TIERS_AUTO INT,
     UTI_GESTION_NUMERO_INS_AUTO INT,
     UTI_GESTION_NUMERO_DOS_AUTO INT,
     UTI_EXPORT_GRAND_ANGLE INT,
     UTI_GA_CHEMIN_EXPORT VARCHAR(250),
     UTI_GA_CHEMIN_IMPORT_RETOUR VARCHAR(250),
     UTI_GA_CHEMIN_IMPORT_TITRE VARCHAR(250),
     UTI_GA_CHEMIN_IMPORT_ENCAI VARCHAR(250),
     UTI_GESTION_DECLARATION INT,
     UTI_GESTION_EXP_CODE_AUTO INT,
     UTI_GESTION_ARRETE INT,
     UTI_CODE_INSEE_COMMUNE VARCHAR(250),
     UTI_CODE_INSEE_DEPARTEMENT VARCHAR(250),
     UTI_GESTIONREGIE INT,
     UTI_MODULE_REGIE_URL VARCHAR(250),
     UTI_GESTION_CA INT,
     UTI_ODP_GEOMETRE INT,
     UTI_CLAVIER_AZERTY INT,
     UTI_GESTION_EMPLOYE INT,
     UTI_GESTION_LOGO_ACCUEIL INT,
     UTI_LOGO_ACCUEIL VARCHAR(250),
     UTI_FEUILLE_RECETTE INT,
     UTI_GESTION_CARTE_BROCANTE INT,
     UTI_GESTION_CARTE_MARCHE INT,
     UTI_FACTURATION_CARTE_BROCANTE INT,
     UTI_EXPORTAREGIE INT,
     UTI_EXPORT_INDIGO_TITRE_VILLE VARCHAR(250),
     UTI_TAS_PDA_TYPE VARCHAR(250),
     UTI_GESTION_TICKET_ANO INT,
     UTI_GESTION_ALERTE_ABS INT,
     UTI_ALERTE_ABS_NB_ABS INT,
     UTI_EXPORT_ONYX INT,
     UTI_EXPORT_ONYX_CHEMIN VARCHAR(250),
     UTI_AJOUT_CLIENT INT,
     UTI_CANDIDATURE_DATE_BLOQUE INT,
     UTI_GESTION_AUT_RECOND_ABO INT,
     UTI_EXPORT_FILIEN_MODELE VARCHAR(250),
     UTI_IMPRESSION_TICKET INT,
     UTI_IMPORT_GEO_ODP INT,
     UTI_EXPORT_FINSAT INT,
     UTI_GESTION_IMPORT_CHARVE INT,
     UTI_CHEMIN_IMPORT_FINSAT VARCHAR(250),
     UTI_GESTION_PRESENCE_ANT INT,
     UTI_AFF_INFO_FACTURATION_CLI INT,
     UTI_AFFBLOC_CONSTAT INT,
     UTI_MODIF_CLIENT INT,
     UTI_GESTION_DLC1 INT,
     UTI_GESTION_DLC2 INT,
     UTI_GESTION_DEVIS_VALORISE INT,
     UTI_AFF_PIECE_JUSTIFICATIF INT,
     UTI_GESTION_REFERENT INT,
     UTI_PDA_AFF_FACTURE INT,
     UTI_GESTION_SEPA INT,
     UTI_IMP_TIKET_INFRACTION INT,
     UTI_PDA_AFF_MULTIPLICATEUR INT,
     UTI_INFO_SAISONNIER INT,
     UTI_GESTION_CORIOLIS INT,
     UTI_AFFICHAGE_RESTE_DU INT,
     UTI_AFF_RECHERCHE_FACTURE INT,
     UTI_GESTION_PRODUIT INT,
     UTI_GESTION_ADRESSE_FAC INT,
     UTI_GESTION_SOUS_DOMAINE INT,
     UTI_GESTION_PES INT,
     UTI_IMP_ETAT_CAISSE INT,
     UTI_GESTION_QTE_MULTI_DEFAUT INT,
     UTI_PDA_AFF_MARCHE_SANS_JOUR INT,
     UTI_AFF_ALERTE_ESPECE INT,
     UTI_GESTION_TYPE_CANDIDATURE INT,
     UTI_EXPORT_CIRIL INT,
     UTI_EXPORT_CIRIL_TIERS INT,
     UTI_GESTION_IMMATRICULATION INT,
     UTI_AFFBLOC_FACTURE_ECHEANCE INT,
     UTI_AFFBLOC_FACTURE_IMPAYE INT,
     UTI_AFFBLOC_ELEMENT_EXPIRE INT,
     UTI_AFFICHAGE_CARTE_BROCANTE INT,
     UTI_VERSEMENT_BORDEREAU_MANDAT INT,
     UTI_GESTION_EXPORT_SHAPEFILE INT,
     UTI_TYPE_EXPORT_SHAPEFILE VARCHAR(250),
     UTI_GESTION_PES_SEPA INT,
     UTI_AFFBLOC_DOSSIER_NONSUIVI INT,
     UTI_EXPORT_FAO_CSV_REFACTION INT,
     UTI_EXPORT_ASTRE INT,
     UTI_GESTION_ZONE_ELEMENT INT,
     UTI_GESTION_ZONE_ELEMENT_TARIF INT,
     UTI_GESTION_IMPORT_ELYX INT,
     UTI_REP_IMPORT_ELYX VARCHAR(250),
     UTI_GESTION_TABLETTE INT,
     UTI_GESTION_PREPA_TOURNEE INT,
     UTI_AFFBLOC_DOSSIER_MODIFIE INT,
     UTI_GEO_LONGITUDE VARCHAR(250),
     UTI_GEO_LATITUDE VARCHAR(250),
     UTI_AFFBLOC_POSE_ILLICITE INT,
     UTI_DATE_VERIF_GEO DATE,
     UTI_GESTIONTAXIS INT,
     UTI_AFFBLOC_ALERTE_TAXIS INT,
     UTI_EXPORT_FILIEN INT,
     UTI_AUT_RECOND_ABO_TYPE INT,
     UTI_AUT_RECOND_ABO_PERIODE VARCHAR(250),
     UTI_GESTION_PES_MET_AUTO INT,
     UTI_EXPORT_ASTRE_MODELE VARCHAR(250),
     UTI_GESTION_NUMERO_DISPO_AUTO INT,
     UTI_GESTION_ECHEANCIER INT,
     UTI_GESTION_VALID_TIERS_FAC INT,
     UTI_GESTION_VALID_TIERS_PES INT,
     UTI_VALIDATION_ENCAISSEMENT INT,
     UTI_CHEMREPTABLETTE VARCHAR(250),
     UTI_GESTIONJARDINS INT,
     UTI_GESTION_TYPOLOGIE INT,
     UTI_GESTION_CONTROLE INT,
     UTI_GESTION_COURRIER_JARDINS INT,
     UTI_GESTION_GESTIONNAIRE INT,
     UTI_GESTION_ETAT_DES_LIEUX INT,
     UTI_GESTION_CHARGE_VARIABLE INT,
     UTI_GESTION_PHOTO_ID_JARDINS INT,
     UTI_GESTION_CANDIDAT_JARDINS INT,
     UTI_GESTION_SECTEUR_ACTIVITE INT,
     UTI_GESTION_ARRHES INT,
     UTI_AFFBLOC_CONTROLE_ELEMENT INT,
     UTI_GESTION_SUIVI_JARDINS INT,
     UTI_PRESENCE_AUTO_SCAN INT,
     UTI_GESTION_DOUBLON INT,
     UTI_GESTION_ABS_PERIODE INT,
     UTI_GESTION_BOREGAR INT,
     UTI_REP_STOCKAGE_WINDOWS VARCHAR(250),
     UTI_REP_STOCKAGE_LINUX VARCHAR(250),
     UTI_CHEMIN_RSX_DONNEES VARCHAR(250),
     UTI_GESTION_MOD_DOC_NAVIGATEUR INT,
     UTI_EXTERNALISATION_ZONE_VILLE INT,
     UTI_AFFBLOC_TIER_VALIDER INT,
     UTI_AFFBLOC_ENCAIS_VALIDER INT,
     UTI_EXPORT_RECAV INT,
     UTI_GESTION_DEPOT_BANQUE INT,
     UTI_VALIDATION_DEPOT_PLACIER INT,
     UTI_EXPORT_SAGE INT,
     UTI_EXPORTAREGIE_TYPE_FICHIER VARCHAR(250),
     UTI_GESTION_COURRIER_TAXIS INT,
     UTI_GESTION_SUIVIDOSSIER_TAXIS INT,
     UTI_GA_CHEMIN_RETOUR_MANDA VARCHAR(250),
     UTI_GA_CHEMIN_RETOUR_REGL VARCHAR(250),
     UTI_GA_CHEMIN_FACTURE_PDF VARCHAR(250),
     UTI_ASTRE_EXPORT_ART_FAC INT,
     UTI_GESTION_EXPORT_CLICMAP INT,
     UTI_GESTION_ORMC_CPP INT,
     UTI_GESTION_VILLE_EMPLOYE INT,
     UTI_AUTHENTIFICATION_WINDOWS INT,
     UTI_SIG_ADRESSE_WS VARCHAR(250),
     UTI_GOOOGLE_MAP_API_KEY VARCHAR(250),
     UTI_GESTION_CORIOLIS_PLA_ODP INT,
     UTI_GESTION_ASSIDU INT,
     UTI_AFFICHAGE_EMPLACEMENT INT,
     UTI_NBR_EMPLACEMENT INT,
     UTI_GESTION_TVA_OBLIG INT,
     UTI_GESTION_ETAT_DOS INT,
     UTI_AFF_NUM_ETAB INT,
     UTI_GESTION_DIV_QUARTIER INT,
     UTI_GESTION_DOC_ADMIN_ELE INT,
     UTI_MODEAFFICHAGECLIENTSTAB VARCHAR(250),
     UTI_SIG_CG92 INT,
     UTI_SIG_AUTOCOMPLETION_WS VARCHAR(250),
     UTI_SIG_GEOCODING_WS VARCHAR(250),
     UTI_SIG_AUTOCOMPLETION_LIMITE INT,
     UTI_SIG_PLAN_WS VARCHAR(250),
     UTI_SIG_TRONCON_WS VARCHAR(250),
     UTI_PDA_CONSUL_PJ INT,
     UTI_EXPORT_ASTRE_TRIMESTRE INT,
     UTI_ETAT_CAISSE_MODELE_PDA VARCHAR(250),
     UTI_GEST_ART_FORFAITAIRE_AUTO INT,
     UTI_GEST_ADRESSE_SMARTPHONE INT,
     UTI_AFF_TRI_FACTURE_MARCHE INT,
     UTI_EXP_CIRIL_PDF INT,
     UTI_AFF_ZONE_RELEVE INT,
     UTI_AFF_DATE_AUTORISATION INT,
     UTI_IMP_MASSE_PH_REL INT,
     UTI_GESTION_ETAT_ELE INT,
     UTI_GESTION_DECISION_ELE INT,
     UTI_GESTION_SUIVI_PART_ELE INT,
     UTI_GEST_MODIF_DAE_FINSAT INT,
     UTI_EXP_GFI INT,
     UTI_EXO_CREATE_DOS INT,
     UTI_TVA_ACOO INT,
     UTI_GEST_PROD_RECOUVREMENT INT,
     UTI_GESTIONNAIRE_RACCOURCI INT,
     UTI_TAXIS_TARIF_ANNUEL VARCHAR(250),
     UTI_GESTION_CANDIDATURE_TAXIS INT,
     UTI_GESTION_EXO_JARDIN INT,
     UTI_CODE_COMPT_BEZIERS INT,
     UTI_RECH_CLIENT_FACT_SMART INT,
     UTI_GESTION_EMPLACEMENT_TICKET INT,
     UTI_GEST_VENTE_TICKET INT,
     UTI_GEST_ABO_PRES INT,
     UTI_GEST_ABO_PRES_REEL INT,
     UTI_GEST_ABO_PRES_ECHEANCE INT,
     UTI_GEST_ABO_PRES_MODELE VARCHAR(250),
     UTI_GEST_ABO_PRE_NB_ABS_JUST VARCHAR(250),
     UTI_GEST_ABO_PRE_PER_ABS_JUST VARCHAR(250),
     UTI_GEST_REGL_ABO_FREQ INT,
     UTI_GEST_ABO_PRES_THEO_REGUL INT,
     UTI_MASQUER_ELE_SANS_RELEVES INT,
     UTI_GESTION_LOGO_EDITION INT,
     UTI_ARCHIVE_FACTURE INT,
     UTI_ARCHIVE_FACTURE_ODP INT,
     UTI_GESTION_LI_ART_TIC_SOLDE INT
);
INSERT INTO dest_utilisateur (UTI_REF,UTI_NOM,UTI_ADRESSE,UTI_CODEPOSTAL,UTI_VILLE,UTI_PAYS,UTI_TELEPHONE,UTI_FAX,UTI_EMAIL,UTI_NUMAGREMENT,UTI_IDENTIFIANT,UTI_MDP_PLATEFORME,UTI_LOGO,UTI_ALERTE,UTI_ALERTE_TIME,UTI_MULTIMARCHE,UTI_GESTION_ELEC,UTI_ABOTITULAIRE_AUTO,UTI_TICKETSTYPES,UTI_CHEMINSITE,UTI_SOCIETECARTE,UTI_ADRESSECARTE,UTI_FACTUREMENSUELLE,UTI_MODEAFFICHAGECLIENTSPDA,UTI_RELANCEFACTURE,UTI_VERSRASFAC,UTI_PDA_RETOURDIRECTSOC,UTI_PDA_TICKETPERIODE,UTI_EXPORT_COMPTABLE,UTI_IMP_TIKET_PRESENCE,UTI_LOGOPDA,UTI_LOGOPDACHEMIN,UTI_GESTION_PLAN,UTI_GESTIONODP,UTI_GESTIONPLACIER,UTI_CHEMREPDONNEES,UTI_GOOGLE_API_KEY,UTI_LDAP,UTI_VERSIONLOGICIEL,UTI_MODELE_FACTURE,UTI_MODELE_TICKET,UTI_GESTIONROLMRE,UTI_TYPEVERSEMENT,UTI_LDAP_DOMAINE,UTI_CODE_GUICHET,UTI_NUMERO_COMPTE,UTI_GESTION_IMPORT,UTI_GESTION_TAS,UTI_GESTION_AUTORISATIONTICKET,UTI_NOM_COLLECTIVITE,UTI_GESTIONSAUVEGARDE,UTI_GESTION_INFRACTION,UTI_AFFBLOC_ENCAISSEMENT,UTI_AFFBLOC_RASSEMBLEMENT,UTI_AFFBLOC_INFRACTION,UTI_GESTIONGENERATION,UTI_IDENTIFIANTCLIENTCOMPTABLE,UTI_LETTREAPPLICATIVE,UTI_MONNAIESUPPORT,UTI_NUMERONATIONALEMETTEUR,UTI_CODEOPERATION,UTI_GESTION_CONSTAT,UTI_MODIF_FACTURE,UTI_GROUPE_TARIF,UTI_IMPRIMANTE_CODEBARRE,UTI_GESTION_SUIVI_DOSSIER,UTI_GESTION_COURRIER,UTI_GESTION_ABONNEMENT,UTI_GESTION_AUTORISATION,DCREAT,UCREAT,UTI_SITE_AIDE_IDENTIFIANT,UTI_SITE_AIDE_MDP,UTI_GESTION_RECU,UTI_EXPORT_BDF,UTI_GESTION_ZONE,UTI_EXTERNALISATION_RUE,UTI_EXPORTSAGA,UTI_GESTION_TARIFPERIODE,UTI_GESTION_NUMTITRE,UTI_GESTION_RECU_AUTOMATIQUE,UTI_GESTION_CANDIDATURE,UTI_GESTION_INSTRUCTION,UTI_GESTION_TAS_PDA,UTI_GESTION_VERSEMENT_RECU,UTI_GESTION_COMMISSION,UTI_GESTION_ARRETE_ELEMENT,UTI_GESTION_PHOTO_ID,UTI_EXPORT_INDIGO_TITRE,UTI_CODE_COLLECTIVITE,UTI_CODE_BUDGET,UTI_GESTION_TVA_BELGE,UTI_GESTION_EXP_NUM_TIERS_AUTO,UTI_GESTION_NUMERO_INS_AUTO,UTI_GESTION_NUMERO_DOS_AUTO,UTI_EXPORT_GRAND_ANGLE,UTI_GA_CHEMIN_EXPORT,UTI_GA_CHEMIN_IMPORT_RETOUR,UTI_GA_CHEMIN_IMPORT_TITRE,UTI_GA_CHEMIN_IMPORT_ENCAI,UTI_GESTION_DECLARATION,UTI_GESTION_EXP_CODE_AUTO,UTI_GESTION_ARRETE,UTI_CODE_INSEE_COMMUNE,UTI_CODE_INSEE_DEPARTEMENT,UTI_GESTIONREGIE,UTI_MODULE_REGIE_URL,UTI_GESTION_CA,UTI_ODP_GEOMETRE,UTI_CLAVIER_AZERTY,UTI_GESTION_EMPLOYE,UTI_GESTION_LOGO_ACCUEIL,UTI_LOGO_ACCUEIL,UTI_FEUILLE_RECETTE,UTI_GESTION_CARTE_BROCANTE,UTI_GESTION_CARTE_MARCHE,UTI_FACTURATION_CARTE_BROCANTE,UTI_EXPORTAREGIE,UTI_EXPORT_INDIGO_TITRE_VILLE,UTI_TAS_PDA_TYPE,UTI_GESTION_TICKET_ANO,UTI_GESTION_ALERTE_ABS,UTI_ALERTE_ABS_NB_ABS,UTI_EXPORT_ONYX,UTI_EXPORT_ONYX_CHEMIN,UTI_AJOUT_CLIENT,UTI_CANDIDATURE_DATE_BLOQUE,UTI_GESTION_AUT_RECOND_ABO,UTI_EXPORT_FILIEN_MODELE,UTI_IMPRESSION_TICKET,UTI_IMPORT_GEO_ODP,UTI_EXPORT_FINSAT,UTI_GESTION_IMPORT_CHARVE,UTI_CHEMIN_IMPORT_FINSAT,UTI_GESTION_PRESENCE_ANT,UTI_AFF_INFO_FACTURATION_CLI,UTI_AFFBLOC_CONSTAT,UTI_MODIF_CLIENT,UTI_GESTION_DLC1,UTI_GESTION_DLC2,UTI_GESTION_DEVIS_VALORISE,UTI_AFF_PIECE_JUSTIFICATIF,UTI_GESTION_REFERENT,UTI_PDA_AFF_FACTURE,UTI_GESTION_SEPA,UTI_IMP_TIKET_INFRACTION,UTI_PDA_AFF_MULTIPLICATEUR,UTI_INFO_SAISONNIER,UTI_GESTION_CORIOLIS,UTI_AFFICHAGE_RESTE_DU,UTI_AFF_RECHERCHE_FACTURE,UTI_GESTION_PRODUIT,UTI_GESTION_ADRESSE_FAC,UTI_GESTION_SOUS_DOMAINE,UTI_GESTION_PES,UTI_IMP_ETAT_CAISSE,UTI_GESTION_QTE_MULTI_DEFAUT,UTI_PDA_AFF_MARCHE_SANS_JOUR,UTI_AFF_ALERTE_ESPECE,UTI_GESTION_TYPE_CANDIDATURE,UTI_EXPORT_CIRIL,UTI_EXPORT_CIRIL_TIERS,UTI_GESTION_IMMATRICULATION,UTI_AFFBLOC_FACTURE_ECHEANCE,UTI_AFFBLOC_FACTURE_IMPAYE,UTI_AFFBLOC_ELEMENT_EXPIRE,UTI_AFFICHAGE_CARTE_BROCANTE,UTI_VERSEMENT_BORDEREAU_MANDAT,UTI_GESTION_EXPORT_SHAPEFILE,UTI_TYPE_EXPORT_SHAPEFILE,UTI_GESTION_PES_SEPA,UTI_AFFBLOC_DOSSIER_NONSUIVI,UTI_EXPORT_FAO_CSV_REFACTION,UTI_EXPORT_ASTRE,UTI_GESTION_ZONE_ELEMENT,UTI_GESTION_ZONE_ELEMENT_TARIF,UTI_GESTION_IMPORT_ELYX,UTI_REP_IMPORT_ELYX,UTI_GESTION_TABLETTE,UTI_GESTION_PREPA_TOURNEE,UTI_AFFBLOC_DOSSIER_MODIFIE,UTI_GEO_LONGITUDE,UTI_GEO_LATITUDE,UTI_AFFBLOC_POSE_ILLICITE,UTI_DATE_VERIF_GEO,UTI_GESTIONTAXIS,UTI_AFFBLOC_ALERTE_TAXIS,UTI_EXPORT_FILIEN,UTI_AUT_RECOND_ABO_TYPE,UTI_AUT_RECOND_ABO_PERIODE,UTI_GESTION_PES_MET_AUTO,UTI_EXPORT_ASTRE_MODELE,UTI_GESTION_NUMERO_DISPO_AUTO,UTI_GESTION_ECHEANCIER,UTI_GESTION_VALID_TIERS_FAC,UTI_GESTION_VALID_TIERS_PES,UTI_VALIDATION_ENCAISSEMENT,UTI_CHEMREPTABLETTE,UTI_GESTIONJARDINS,UTI_GESTION_TYPOLOGIE,UTI_GESTION_CONTROLE,UTI_GESTION_COURRIER_JARDINS,UTI_GESTION_GESTIONNAIRE,UTI_GESTION_ETAT_DES_LIEUX,UTI_GESTION_CHARGE_VARIABLE,UTI_GESTION_PHOTO_ID_JARDINS,UTI_GESTION_CANDIDAT_JARDINS,UTI_GESTION_SECTEUR_ACTIVITE,UTI_GESTION_ARRHES,UTI_AFFBLOC_CONTROLE_ELEMENT,UTI_GESTION_SUIVI_JARDINS,UTI_PRESENCE_AUTO_SCAN,UTI_GESTION_DOUBLON,UTI_GESTION_ABS_PERIODE,UTI_GESTION_BOREGAR,UTI_REP_STOCKAGE_WINDOWS,UTI_REP_STOCKAGE_LINUX,UTI_CHEMIN_RSX_DONNEES,UTI_GESTION_MOD_DOC_NAVIGATEUR,UTI_EXTERNALISATION_ZONE_VILLE,UTI_AFFBLOC_TIER_VALIDER,UTI_AFFBLOC_ENCAIS_VALIDER,UTI_EXPORT_RECAV,UTI_GESTION_DEPOT_BANQUE,UTI_VALIDATION_DEPOT_PLACIER,UTI_EXPORT_SAGE,UTI_EXPORTAREGIE_TYPE_FICHIER,UTI_GESTION_COURRIER_TAXIS,UTI_GESTION_SUIVIDOSSIER_TAXIS,UTI_GA_CHEMIN_RETOUR_MANDA,UTI_GA_CHEMIN_RETOUR_REGL,UTI_GA_CHEMIN_FACTURE_PDF,UTI_ASTRE_EXPORT_ART_FAC,UTI_GESTION_EXPORT_CLICMAP,UTI_GESTION_ORMC_CPP,UTI_GESTION_VILLE_EMPLOYE,UTI_AUTHENTIFICATION_WINDOWS,UTI_SIG_ADRESSE_WS,UTI_GOOOGLE_MAP_API_KEY,UTI_GESTION_CORIOLIS_PLA_ODP,UTI_GESTION_ASSIDU,UTI_AFFICHAGE_EMPLACEMENT,UTI_NBR_EMPLACEMENT,UTI_GESTION_TVA_OBLIG,UTI_GESTION_ETAT_DOS,UTI_AFF_NUM_ETAB,UTI_GESTION_DIV_QUARTIER,UTI_GESTION_DOC_ADMIN_ELE,UTI_MODEAFFICHAGECLIENTSTAB,UTI_SIG_CG92,UTI_SIG_AUTOCOMPLETION_WS,UTI_SIG_GEOCODING_WS,UTI_SIG_AUTOCOMPLETION_LIMITE,UTI_SIG_PLAN_WS,UTI_SIG_TRONCON_WS,UTI_PDA_CONSUL_PJ,UTI_EXPORT_ASTRE_TRIMESTRE,UTI_ETAT_CAISSE_MODELE_PDA,UTI_GEST_ART_FORFAITAIRE_AUTO,UTI_GEST_ADRESSE_SMARTPHONE,UTI_AFF_TRI_FACTURE_MARCHE,UTI_EXP_CIRIL_PDF,UTI_AFF_ZONE_RELEVE,UTI_AFF_DATE_AUTORISATION,UTI_IMP_MASSE_PH_REL,UTI_GESTION_ETAT_ELE,UTI_GESTION_DECISION_ELE,UTI_GESTION_SUIVI_PART_ELE,UTI_GEST_MODIF_DAE_FINSAT,UTI_EXP_GFI,UTI_EXO_CREATE_DOS,UTI_TVA_ACOO,UTI_GEST_PROD_RECOUVREMENT,UTI_GESTIONNAIRE_RACCOURCI,UTI_TAXIS_TARIF_ANNUEL,UTI_GESTION_CANDIDATURE_TAXIS,UTI_GESTION_EXO_JARDIN,UTI_CODE_COMPT_BEZIERS,UTI_RECH_CLIENT_FACT_SMART,UTI_GESTION_EMPLACEMENT_TICKET,UTI_GEST_VENTE_TICKET,UTI_GEST_ABO_PRES,UTI_GEST_ABO_PRES_REEL,UTI_GEST_ABO_PRES_ECHEANCE,UTI_GEST_ABO_PRES_MODELE,UTI_GEST_ABO_PRE_NB_ABS_JUST,UTI_GEST_ABO_PRE_PER_ABS_JUST,UTI_GEST_REGL_ABO_FREQ,UTI_GEST_ABO_PRES_THEO_REGUL,UTI_MASQUER_ELE_SANS_RELEVES,UTI_GESTION_LOGO_EDITION,UTI_ARCHIVE_FACTURE,UTI_ARCHIVE_FACTURE_ODP,UTI_GESTION_LI_ART_TIC_SOLDE) values ('1','A définir',null,null,null,'France',null,null,null,null,'geodpthibaut','geodpthibaut',null,'0','0','0','0','0','1','http://localhost/geodp.thibaut/','0',null,'0','Marche','0','1','1','0','null','0','0',null,'0','0','1','C:/inetpub/wwwroot/geodp.thibaut/donnees/',null,'0','prod',null,'defaut','0','0',null,null,null,'0','0','0',null,'0','0','0','0','0','1',null,null,null,null,null,'0','0','0',null,'0','0','0','0',CURDATE(),'iltr',null,null,'0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0',null,null,'0','0','0','0','0',null,null,null,null,'0','1','0',null,null,'0',null,'0','0','0','0','0',null,'0','0','0','0','0',null,'auto','0','0','0','0',null,'0','0','0',null,'1','0','0','0',null,'0','1','0','1','0','0','0','0','0','0','0','1','1','0','0','0','3','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0','0','0','0',null,'0','0','0','0','0','0','0',null,'0','0','0','-0.5629345','47.4818884','0',CURDATE(),'0','0','0','0',null,'0',null,'0','0','0','0','0',null,'0','0','0','0','0','0','0','0','0','0','0','0','1','0','0','0','0',null,null,null,'0','0','0','0','0','0','0','0','xml','1','1',null,null,null,'0','0','0','0','0',null,null,'0','0','0',null,'0','0','0','0','0',null,'0',null,null,'0',null,null,'0','0',null,'0','0','0','0','0','0','0','0','0','0','0','0','0','0','0',null,null,'0','0','0','0','0','0','0','0','0',null,null,null,'0','0','0','0','1','1','0');

CREATE TABLE IF NOT EXISTS `dest_employe`
(
    EMP_REF           INT,
    FEM_REF           INT,
    UTI_REF           INT,
    GA_REF            INT,
    EMP_NOM           VARCHAR(250),
    EMP_MDP           VARCHAR(250),
    EMP_PRENOM        VARCHAR(250),
    EMP_ADRESSE       VARCHAR(250),
    EMP_CODEPOSTAL    VARCHAR(250),
    EMP_VILLE         VARCHAR(250),
    EMP_TELEPHONE     VARCHAR(250),
    EMP_PORTABLE      VARCHAR(250),
    EMP_FAX           VARCHAR(250),
    EMP_EMAIL         VARCHAR(250),
    EMP_ADMIN         INT,
    EMP_MASQUE        INT,
    EMP_VISIBLE       INT,
    EMP_LOGIN         VARCHAR(250),
    EMP_FONCTION      VARCHAR(250),
    DCREAT            DATE,
    UCREAT            VARCHAR(250),
    CIV_REF           INT,
    LAN_REF           INT,
    EMP_INSTRUCTEUR   INT,
    EMP_PDA_PLACIER   INT,
    EMP_PDA_ODP       INT
);
INSERT INTO dest_employe (EMP_REF,FEM_REF,UTI_REF,GA_REF,EMP_NOM,EMP_MDP,EMP_PRENOM,EMP_ADRESSE,EMP_CODEPOSTAL,EMP_VILLE,EMP_TELEPHONE,EMP_PORTABLE,EMP_FAX,EMP_EMAIL,EMP_ADMIN,EMP_MASQUE,EMP_VISIBLE,EMP_LOGIN,EMP_FONCTION,DCREAT,UCREAT,CIV_REF,LAN_REF,EMP_INSTRUCTEUR,EMP_PDA_PLACIER,EMP_PDA_ODP) values ('1',null,'1','4','iltr','95c5642e68a3fd378d7c0913e1f6765b',null,null,null,null,null,null,null,null,'2','1','1',null,null,null,null,null,'1','0','1','1');

CREATE TABLE IF NOT EXISTS `dest_employe_marche`
(
    EMA_REF           INT,
    EMP_REF           INT,
    MAR_REF           INT,
    DCREAT            DATE,
    UCREAT            VARCHAR(250),
    ACT_REF           INT
);
INSERT INTO dest_employe_marche (EMA_REF,EMP_REF,MAR_REF,DCREAT,UCREAT,ACT_REF) values ('1','1',null,CURDATE(),'iltr','1');

CREATE TABLE IF NOT EXISTS `dest_marche`
(
    MAR_REF        INT,
    UTI_REF        INT,
    ACT_REF        INT,
    DOM_REF        INT,
    MAR_VILLE      VARCHAR(250),
    MAR_JOUR       VARCHAR(250),
    MAR_CPTFACTURE INT,
    MAR_COMPTE     VARCHAR(250),
    MAR_VISIBLE    INT,
    MAR_MAT        INT,
    MAR_CODE       VARCHAR(250),
    MAR_DATECREATION DATE,
    MAR_POINTEAU    INT,
    MAR_TOILETTE    INT,
    MAR_ELECTRICITE INT,
    MAR_ELECT_DATE_MEP DATE,
    MAR_ELECT_DATE_DVI DATE,
    MAR_NBEMPLACEMENT        INT,
    MAR_LINEAIREMAX          VARCHAR(250),
    MAR_SURFACEMAX           VARCHAR(250),
    MAR_REGIEQUARTIER        INT,
    MAR_SERVICEMUNICIPAL     INT,
    MAR_COMMENTAIRE          VARCHAR(250),
    MAR_REGQUART_RESPONSABLE VARCHAR(250),
    MAR_REGQUART_TELEPHONE   VARCHAR(250),
    MAR_SERVMUNI_RESPONSABLE VARCHAR(250),
    MAR_SERVMUNI_TELEPHONE   VARCHAR(250),
    MAR_ADJOINTQUARTIER      VARCHAR(250),
    MAR_NUMEROARRETE         VARCHAR(250),
    DCREAT DATE,
    UCREAT                     VARCHAR(250),
    MAR_PERIODE_GENERATION_ABO VARCHAR(250),
    SDO_REF                    INT,
    TPO_REF                    INT,
    GST_REF                    INT,
    MAR_ADRESSE                VARCHAR(250),
    MAR_CHARGE_VARIABLE        INT,
    ART_REF                    INT,
    MAR_VALIDE                 INT
);

CREATE TABLE IF NOT EXISTS `dest_marche_langue`
(
    MAR_REF           INT,
    LAN_REF           INT,
    MAR_NOM           VARCHAR(250),
    MAR_TICKET_ENTETE VARCHAR(250),
    MAR_TICKET_PIED   VARCHAR(250),
    DCREAT DATE,
    UCREAT VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS `dest_article`
(
    ART_REF            INT,
    MAR_REF            INT,
    ART_ART_REF        INT,
    UTI_REF            INT,
    ART_CODE           VARCHAR(250),
    ART_CODE_COMPTABLE VARCHAR(250),
    ART_PRIX_TTC       FLOAT,
    ART_PRIX_HT        FLOAT,
    ART_TAUX_TVA       FLOAT,
    ART_ABO_PRIX_TTC   FLOAT,
    ART_ABO_PRIX_HT    FLOAT,
    ART_ABO_TAUX_TVA   FLOAT,
    ART_COULEUR        VARCHAR(250),
    ART_ORDRE          INT,
    ART_COMMENTAIRE    VARCHAR(250),
    ART_VALIDE_DEPUIS DATE,
    ART_VALIDE_JUSQUA DATE,
    ART_VISIBLE           INT,
    ART_RELEVE_ELEC       INT,
    ART_TYPE_TARIFICATION VARCHAR(250),
    ART_QUANTITE_MODIF    INT,
    ART_RECONDUCTIBLE     INT,
    DCREAT DATE,
    UCREAT                    VARCHAR(250),
    ART_QUANTITE_DEFAUT       INT,
    ART_MULTIPLICATEUR_DEFAUT INT,
    CHV_REF                   INT,
    ART_CODE_COMPTABLE_TVA    VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS `dest_article_langue`
(
    ART_REF   INT,
    LAN_REF   INT,
    ART_NOM   VARCHAR(250),
    ART_UNITE VARCHAR(250),
    DCREAT DATE,
    UCREAT VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS `dest_exploitant`
(
    EXP_REF                   INT,
    UTI_REF                   INT,
    GRA_REF                   INT,
    CAT_REF                   INT,
    NAT_REF                   INT,
    CIV_REF                   INT,
    LAN_REF                   INT,
    ETP_REF                   INT,
    ACO_REF                   INT,
    ACOO_REF                  INT,
    EXP_NOM_PERS_PHYSIQUE     VARCHAR(250),
    EXP_PRENOM_PERS_PHYSIQUE  VARCHAR(250),
    EXP_RAISON_SOCIALE        VARCHAR(250),
    EXP_NOM                   VARCHAR(250),
    EXP_ENSEIGNE              VARCHAR(250),
    EXP_SIRET                 VARCHAR(250),
    EXP_CODE                  VARCHAR(250),
    EXP_CODE_COMPTABLE        VARCHAR(250),
    EXP_APE                   VARCHAR(250),
    EXP_TVAINTRACOMMUNAUTAIRE VARCHAR(250),
    EXP_VISIBLE               INT,
    EXP_VALIDE                INT,
    EXP_DATE_CESSATION DATE,
    EXP_NRUE              INT,
    EXP_NRUE_ALPHA        VARCHAR(250),
    EXP_ADRESSE           VARCHAR(250),
    EXP_CP                VARCHAR(250),
    EXP_VILLE             VARCHAR(250),
    PA_REF                INT,
    RUE_REF               INT,
    EXP_COMPLEMENTADRESSE VARCHAR(250),
    EXP_TELEPHONE         VARCHAR(250),
    EXP_PORTABLE          VARCHAR(250),
    EXP_FAX               VARCHAR(250),
    EXP_COMMENTAIRE       VARCHAR(250),
    EXP_EMAIL             VARCHAR(250),
    EXP_TITULAIRECOMPTE   VARCHAR(250),
    EXP_IBAN              VARCHAR(250),
    EXP_BIC               VARCHAR(250),
    EXP_SEPA_NUMERO_RUM   VARCHAR(250),
    EXP_SEPA_SIGNATURE_MANDAT DATE,
    EXP_PRODUCTEUR INT,
    EXP_DATE_NAISSANCE DATE,
    EXP_PHOTO_IDENTITE VARCHAR(250),
    EXP_CODERUEGDA     VARCHAR(250),
    EXP_CREATION DATE,
    EXP_MODIFICATION DATE,
    DCREAT DATE,
    UCREAT                    VARCHAR(250),
    ANC_EXP_REF               INT,
    EXP_LIEU_NAISSANCE        VARCHAR(250),
    EXP_DEPARTEMENT_NAISSANCE VARCHAR(250),
    PAN_REF                   INT,
    EXP_NUM_AGREMENT          VARCHAR(250),
    EXP_REFERENCE_RCS         VARCHAR(250),
    EXP_PERMIS_DATE DATE,
    EXP_PERMIS_LIEU           VARCHAR(250),
    EXP_PERMIS_AUT_DELIVRANCE VARCHAR(250),
    EXP_PERMIS_DATE_FIN DATE,
    EXP_CARTE_PRO_NUMERO VARCHAR(250),
    EXP_CARTE_PRO_DATE DATE,
    EXP_CARTE_PRO_DATE_FIN DATE,
    EXP_FORMATION_CONT_DATE_FIN DATE,
    EXP_TYPE_TAXIS      INT,
    EXP_COMPLEMENT_NOM  VARCHAR(250),
    EXP_TIERS_A_VALIDER INT,
    EXP_TIERS_VALIDE    INT
);

CREATE TABLE IF NOT EXISTS `dest_societe_marche`
(
    EXP_REF       INT,
    MAR_REF       INT,
    ACO_REF       INT,
    SMA_TITULAIRE INT,
    SMA_TITULAIRE_DATE DATE,
    SMA_EMPLACEMENT VARCHAR(250),
    SMA_CESSATION   INT,
    SMA_CESSATION_DATE DATE,
    SMA_CANDIDATURE INT,
    SMA_CANDIDATURE_DATE_DEBUT DATE,
    SMA_CONDITION VARCHAR(250),
    SMA_METRAGE   VARCHAR(250),
    SMA_DATEDEBUT DATE,
    SMA_PRODUCTEUR      INT,
    SMA_ARTICLEAUTORISE VARCHAR(250),
    SMA_ABONNE          INT,
    SMA_ABONNE_DATE DATE,
    DCREAT DATE,
    UCREAT VARCHAR(250),
    SMA_DATE_REINI_PRESENCE DATE,
    SMA_CANDIDATURE_DATE_FIN DATE,
    SMA_CANDIDATURE_COMMENTAIRE  VARCHAR(250),
    SMA_CANDIDATURE_FICHIER      VARCHAR(250),
    SMA_NB_PRESENCES_ANTERIEURES INT,
    SMA_REFERENT                 INT,
    SMA_SAISONNIER               INT,
    SMA_NUMERO_CONTRAT           INT
);

CREATE TABLE IF NOT EXISTS `dest_activitecommerciale`
(
    ACO_REF     INT,
    UTI_REF     INT,
    ACO_COULEUR VARCHAR(250),
    ACO_ACO_REF INT,
    ACO_GROUPE  INT,
    DCREAT DATE,
    UCREAT VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS `dest_activitecommerciale_langue`
(
    ACO_REF INT,
    LAN_REF INT,
    ACO_NOM VARCHAR(250),
    DCREAT DATE,
    UCREAT VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS `dest_societe_propriete`
(
    PROP_REF INT,
    ACT_REF INT,
    ACO_REF INT,
    UTI_REF INT,
    DCREAT DATE,
    UCREAT VARCHAR(250),
    PROP_GENERE_ALERT_PDA INT
);

CREATE TABLE IF NOT EXISTS `dest_societe_propriete_langue`
(
    PROP_REF INT,
    LAN_REF INT,
    PROP_NOM VARCHAR(250),
    DCREAT DATE,
    UCREAT VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS `dest_societe_propriete_valeur`
(
    EXP_REF INT,
    PROP_REF INT,
    PROP_VALEUR VARCHAR(250),
    PROP_DATE DATE,
    PROP_DATE_VALIDITE DATE,
    PROP_FICHIER VARCHAR(250),
    DCREAT DATE,
    UCREAT VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS `reprise_placier`
(
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `token` varchar(250) DEFAULT NULL COMMENT 'md5 de la première ligne des données du fichier des marchés',
  `nom` varchar(50) DEFAULT NULL,
  `date_debut` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_fin` timestamp NULL DEFAULT NULL,
  `etat` int(2) NOT NULL COMMENT '0 = Initialisation en cours, 1 = Analyse en cours, 2 = Terminée, 3 = Interrompue',
  `marches_src` int(11) NOT NULL DEFAULT '0',
  `articles_src` int(11) NOT NULL DEFAULT '0',
  `exploitants_src` int(11) NOT NULL DEFAULT '0',
  `marches_dest` int(11) NOT NULL DEFAULT '0',
  `articles_dest` int(11) NOT NULL DEFAULT '0',
  `exploitants_dest` int(11) NOT NULL DEFAULT '0',
  `conflits` int(11) NOT NULL DEFAULT '0',
  `erreurs` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `reprise_odp`
(
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `token` varchar(250) DEFAULT NULL COMMENT 'md5 de la première ligne des données du fichier des marchés',
  `nom` varchar(50) DEFAULT NULL,
  `date_debut` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_fin` timestamp NULL DEFAULT NULL,
  `etat` int(2) NOT NULL COMMENT '0 = Initialisation en cours, 1 = Analyse en cours, 2 = Terminée, 3 = Interrompue',
  `instructions_src` int(11) NOT NULL DEFAULT '0',
  `instructions_dest` int(11) NOT NULL DEFAULT '0',
  `conflits` int(11) NOT NULL DEFAULT '0',
  `erreurs` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
);


-- DELETE FROM dest_marche;
-- DELETE FROM dest_marche_langue;
-- DELETE FROM dest_article;
-- DELETE FROM dest_article_langue;
-- DELETE FROM dest_exploitant;
-- DELETE FROM dest_societe_marche;
-- DELETE FROM dest_activitecommerciale;
-- DELETE FROM dest_activitecommerciale_langue;
-- DELETE FROM dest_societe_propriete;
-- DELETE FROM dest_societe_propriete_langue;
-- DELETE FROM dest_societe_propriete_valeur;
