DROP TABLE fiscalites_villes_nul;
DROP TABLE fiscalites_villes;
CREATE TABLE fiscalites_villes_nul
(
    annee varchar(255),
    type_zone varchar(255),
    nom varchar(255),
    population varchar(255),
    cog varchar(255),
    url varchar(255),
    taxe_add_1 varchar(255),
    taxe_add_2 varchar(255),
    taxe_add_3 varchar(255),
    taxe_add_4 varchar(255),
    avance varchar(255),
    dotation_fonctionnement varchar(255),
    impositions_forfaitaires_1 varchar(255),
    impositions_forfaitaires_2 varchar(255),
    impositions_forfaitaires_3 varchar(255),
    impositions_forfaitaires_4 varchar(255),
    cotisation_va_1 varchar(255),
    cotisation_va_2 varchar(255),
    cotisation_va_3 varchar(255),
    cotisation_va_4 varchar(255),
    cotisation_fonciere_1 varchar(255),
    cotisation_fonciere_2 varchar(255),
    cotisation_fonciere_3 varchar(255),
    cotisation_fonciere_4 varchar(255),
    taxe_pro_1 varchar(255),
    taxe_pro_2 varchar(255),
    taxe_pro_3 varchar(255),
    taxe_pro_4 varchar(255),
    contingents varchar(255),
    charges varchar(255),
    annuite_dette varchar(255),
    encours_dette varchar(255),
    caf_nette varchar(255),
    remboursement_emprunts varchar(255),
    depenses_equipement varchar(255),
    fctva varchar(255),
    charges_financieres varchar(255),
    capacite_financement_1 varchar(255),
    immobilisations varchar(255),
    resultat varchar(255),
    taxe_hab_1 varchar(255),
    taxe_hab_2 varchar(255),
    taxe_hab_3 varchar(255),
    taxe_hab_4 varchar(255),
    total_ressources_inv varchar(255),
    total_emplois_inv varchar(255),
    taxe_fonciere_1 varchar(255),
    taxe_fonciere_2 varchar(255),
    taxe_fonciere_3 varchar(255),
    taxe_fonciere_4 varchar(255),
    emprunts_bancaires varchar(255),
    impots_locaux varchar(255),
    resultat_comptable varchar(255),
    total_charges_fct varchar(255),
    total_produits_fct varchar(255),
    autres_impots_taxes varchar(255),
    subventions_versees varchar(255),
    taxe_fonciere_5 varchar(255),
    taxe_fonciere_6 varchar(255),
    taxe_fonciere_7 varchar(255),
    taxe_fonciere_8 varchar(255),
    charges_externes varchar(255),
    subventions_recues varchar(255),
    capacite_financement_2 varchar(255),
    taxe_surfaces_1 varchar(255),
    taxe_surfaces_2 varchar(255),
    taxe_surfaces_3 varchar(255),
    taxe_surfaces_4 varchar(255),
    retour_biens varchar(255),
    caf varchar(255),
    charges_personnel varchar(255),
    excedent_brut_fct varchar(255),
    solde_op varchar(255),
    fonds_roulement varchar(255)
);
-- Une fois le script BigDump utilisé, copier les valeurs de la table fiscalites_villes_nul dans la table définitive fiscalites_villes (qui, elle, est correctement typée)
    -- NON, ca marche pas
    -- Renommer la table fiscalites_villes_nul en fiscalites_villes
    RENAME TABLE fiscalites_villes_nul TO fiscalites_villes;
CREATE TABLE fiscalites_villes
(
    annee int,
    type_zone varchar(255),
    nom varchar(255),
    population int,
    cog int,
    url varchar(255),
    taxe_add_1 int DEFAULT 0,
    taxe_add_2 int DEFAULT 0,
    taxe_add_3 int DEFAULT 0,
    taxe_add_4 int DEFAULT 0,
    avance int DEFAULT 0,
    dotation_fonctionnement int DEFAULT 0,
    impositions_forfaitaires_1 int DEFAULT 0,
    impositions_forfaitaires_2 int DEFAULT 0,
    impositions_forfaitaires_3 int DEFAULT 0,
    impositions_forfaitaires_4 int DEFAULT 0,
    cotisation_va_1 int DEFAULT 0,
    cotisation_va_2 int DEFAULT 0,
    cotisation_va_3 int DEFAULT 0,
    cotisation_va_4 int DEFAULT 0,
    cotisation_fonciere_1 int DEFAULT 0,
    cotisation_fonciere_2 int DEFAULT 0,
    cotisation_fonciere_3 int DEFAULT 0,
    cotisation_fonciere_4 int DEFAULT 0,
    taxe_pro_1 int DEFAULT 0,
    taxe_pro_2 int DEFAULT 0,
    taxe_pro_3 int DEFAULT 0,
    taxe_pro_4 int DEFAULT 0,
    contingents int DEFAULT 0,
    charges int DEFAULT 0,
    annuite_dette int DEFAULT 0,
    encours_dette int DEFAULT 0,
    caf_nette int DEFAULT 0,
    remboursement_emprunts int DEFAULT 0,
    depenses_equipement int DEFAULT 0,
    fctva int DEFAULT 0,
    charges_financieres int DEFAULT 0,
    capacite_financement_1 int DEFAULT 0,
    immobilisations int DEFAULT 0,
    resultat int DEFAULT 0,
    taxe_hab_1 int DEFAULT 0,
    taxe_hab_2 int DEFAULT 0,
    taxe_hab_3 int DEFAULT 0,
    taxe_hab_4 int DEFAULT 0,
    total_ressources_inv int DEFAULT 0,
    total_emplois_inv int DEFAULT 0,
    taxe_fonciere_1 int DEFAULT 0,
    taxe_fonciere_2 int DEFAULT 0,
    taxe_fonciere_3 int DEFAULT 0,
    taxe_fonciere_4 int DEFAULT 0,
    emprunts_bancaires int DEFAULT 0,
    impots_locaux int DEFAULT 0,
    resultat_comptable int DEFAULT 0,
    total_charges_fct int DEFAULT 0,
    total_produits_fct int DEFAULT 0,
    autres_impots_taxes int DEFAULT 0,
    subventions_versees int DEFAULT 0,
    taxe_fonciere_5 int DEFAULT 0,
    taxe_fonciere_6 int DEFAULT 0,
    taxe_fonciere_7 int DEFAULT 0,
    taxe_fonciere_8 int DEFAULT 0,
    charges_externes int DEFAULT 0,
    subventions_recues int DEFAULT 0,
    capacite_financement_2 int DEFAULT 0,
    taxe_surfaces_1 int DEFAULT 0,
    taxe_surfaces_2 int DEFAULT 0,
    taxe_surfaces_3 int DEFAULT 0,
    taxe_surfaces_4 int DEFAULT 0,
    retour_biens int DEFAULT 0,
    caf int DEFAULT 0,
    charges_personnel int DEFAULT 0,
    excedent_brut_fct int DEFAULT 0,
    solde_op int DEFAULT 0,
    fonds_roulement int
);
INSERT INTO fiscalites_villes SELECT * FROM fiscalites_villes_nul;