CREATE TABLE correspondances_fiscalites
(
champ VARCHAR(255) PRIMARY KEY,
signification VARCHAR(255)
);

INSERT INTO correspondances_fiscalites VALUES
('annee','année'),
('type_zone','type de zone administrative'),
('nom','nom'),
('population','population'),
('cog','cog (code officiel géographique)'),
('url','url'),
('taxe_add_1','taxe additionnelle à la taxe foncière sur les propriétés non bâties - base nette imposée'),
('taxe_add_2','taxe additionnelle à la taxe foncière sur les propriétés non bâties - réductions de bases accordées sur délibérations'),
('taxe_add_3','taxe additionnelle à la taxe foncière sur les propriétés non bâties - taux'),
('taxe_add_4','taxe additionnelle à la taxe foncière sur les propriétés non bâties - produits'),
('avance','avances du trésor au 31/12/n'),
('dotation_fonctionnement','dotation globale de fonctionnement'),
('impositions_forfaitaires_1','impositions forfaitaires sur les entreprises de réseau - base nette imposée'),
('impositions_forfaitaires_2','impositions forfaitaires sur les entreprises de réseau - réductions de bases accordées sur délibérations'),
('impositions_forfaitaires_3','impositions forfaitaires sur les entreprises de réseau - taux'),
('impositions_forfaitaires_4','impositions forfaitaires sur les entreprises de réseau - produits'),
('cotisation_va_1','cotisation sur la valeur ajoutée des entreprises - base nette imposée'),
('cotisation_va_2','cotisation sur la valeur ajoutée des entreprises - réductions de bases accordées sur délibérations'),
('cotisation_va_3','cotisation sur la valeur ajoutée des entreprises - taux'),
('cotisation_va_4','cotisation sur la valeur ajoutée des entreprises - produits'),
('cotisation_fonciere_1','cotisation foncière des entreprises - base nette imposée'),
('cotisation_fonciere_2','cotisation foncière des entreprises - réductions de bases accordées sur délibérations'),
('cotisation_fonciere_3','cotisation foncière des entreprises - taux'),
('cotisation_fonciere_4','cotisation foncière des entreprises - produits'),
('taxe_pro_1','taxe professionnelle (hors bases écrêtées) - base nette imposée'),
('taxe_pro_2','taxe professionnelle (hors bases écrêtées) - réductions de bases accordées sur délibérations'),
('taxe_pro_3','taxe professionnelle (hors bases écrêtées) - taux'),
('taxe_pro_4','taxe professionnelle (hors bases écrêtées) - produits'),
('contingents','contingents'),
('charges','charges à répartir'),
('annuite_dette','annuité de la dette'),
('encours_dette','encours total de la dette au 31/12/n'),
('caf_nette','caf nette du remboursement en capital des emprunts'),
('remboursement_emprunts','remboursement d\'emprunts et dettes assimilées'),
('depenses_equipement','dépenses d\'équipement'),
('fctva','fctva'),
('charges_financieres','charges financières'),
('capacite_financement_1','= besoin ou capacité de financement de la section d\'investissement = e'),
('immobilisations','immobilisations affectées / concédées / etc'),
('resultat','résultat d\'ensemble = r - e'),
('taxe_hab_1','taxe d\'habitation (y compris thlv) - base nette imposée'),
('taxe_hab_2','taxe d\'habitation (y compris thlv) - réductions de bases accordées sur délibérations'),
('taxe_hab_3','taxe d\'habitation (y compris thlv) - taux'),
('taxe_hab_4','taxe d\'habitation (y compris thlv) - produits'),
('total_ressources_inv','total des ressources d\'investissement = c'),
('total_emplois_inv','total des emplois d\'investissement = d'),
('taxe_fonciere_1','taxe foncière sur les propriétés non bâties - base nette imposée'),
('taxe_fonciere_2','taxe foncière sur les propriétés non bâties - réductions de bases accordées sur délibérations'),
('taxe_fonciere_3','taxe foncière sur les propriétés non bâties - taux'),
('taxe_fonciere_4','taxe foncière sur les propriétés non bâties - produits'),
('emprunts_bancaires','emprunts bancaires et dettes assimilées'),
('impots_locaux','impôts locaux'),
('resultat_comptable','resultat comptable = a - b = r'),
('total_charges_fct','total des charges de fonctionnement = b'),
('total_produits_fct','total des produits de fonctionnement = a'),
('autres_impots_taxes','autres impôts et taxes'),
('subventions_versees','subventions versées'),
('taxe_fonciere_5','taxe foncière sur les propriétés bâties - base nette imposée'),
('taxe_fonciere_6','taxe foncière sur les propriétés bâties - réductions de bases accordées sur délibérations'),
('taxe_fonciere_7','taxe foncière sur les propriétés bâties - taux'),
('taxe_fonciere_8','taxe foncière sur les propriétés bâties - produits'),
('charges_externes','achats et charges externes'),
('subventions_recues','subventions reçues'),
('capacite_financement_2','besoin ou capacité de financement résiduel de la section d\'investissement = d - c'),
('taxe_surfaces_1','taxe sur les surfaces commerciales - base nette imposée'),
('taxe_surfaces_2','taxe sur les surfaces commerciales - réductions de bases accordées sur délibérations'),
('taxe_surfaces_3','taxe sur les surfaces commerciales - taux'),
('taxe_surfaces_4','taxe sur les surfaces commerciales - produits'),
('retour_biens','retour de biens affectés / concédés / etc'),
('caf','capacité d\'autofinancement = caf'),
('charges_personnel','charges de personnel'),
('excedent_brut_fct','excédent brut de fonctionnement'),
('solde_op','solde des opérations pour le compte de tiers'),
('fonds_roulement','fonds de roulement');
